import base64
from pathlib import Path
from src.config.constants import DEFAULT_VISION_MODEL
from langchain.chat_models import init_chat_model
from langchain_core.messages import HumanMessage

from src.utils.usage_aggregator_callback import UsageAggregatorCallback


class OllamaVisionClient:
    def __init__(
        self,
        model: str = DEFAULT_VISION_MODEL,
        base_url: str = "http://localhost:11434",
    ) -> None:
        self.model = model
        self.base_url = base_url.rstrip("/")
        self._vision_llm = None

    def _ensure_vision_llm(self):
        if self._vision_llm is not None:
            return self._vision_llm

        global_usage_aggregator = UsageAggregatorCallback("ollama_vision_calls")

        self._vision_llm = init_chat_model(
            model=self.model,
            temperature=0,
            base_url=self.base_url,
            configurable_fields="any",
            callbacks=[global_usage_aggregator],
        )
        return self._vision_llm

    def _invoke_multimodal(self, prompt: str, image_b64: str) -> str:
        llm = self._ensure_vision_llm()
        message = HumanMessage(
            content=[
                {"type": "text", "text": prompt},
                {
                    "type": "image_url",
                    "image_url": f"data:image/png;base64,{image_b64}",
                },
            ]
        )
        response = llm.invoke([message])
        content = getattr(response, "content", "")

        if isinstance(content, str):
            return content.strip()

        if isinstance(content, list):
            text_parts: list[str] = []
            for item in content:
                if isinstance(item, dict):
                    if item.get("type") == "text" and item.get("text"):
                        text_parts.append(str(item["text"]).strip())
                elif isinstance(item, str):
                    text_parts.append(item.strip())
            return "\n".join(part for part in text_parts if part).strip()

        return str(content).strip()

    def describe_image(self, image_path: Path, caption_hint: str = "") -> str:
        with image_path.open("rb") as image_file:
            image_bytes = image_file.read()

        image_b64 = base64.b64encode(image_bytes).decode("ascii")

        prompt = (
            "You are describing a research-paper figure for a RAG system. "
            "Describe the figure content, key entities, trends, labels, and technical takeaway in 4-7 sentences. "
            "Do not hallucinate text that is not visible."
        )
        if caption_hint:
            prompt = f"{prompt} Caption hint: {caption_hint}"

        description = self._invoke_multimodal(prompt=prompt, image_b64=image_b64)
        if description:
            return description

        return "No visual description generated by the vision model."

    def transcribe_formula_latex(self, image_path: Path, formula_hint: str = "") -> str:
        with image_path.open("rb") as image_file:
            image_bytes = image_file.read()

        image_b64 = base64.b64encode(image_bytes).decode("ascii")

        prompt = (
            "You are a precise OCR assistant for mathematical expressions. "
            "Transcribe the equation in this image into valid LaTeX. "
            "Return only the LaTeX expression without markdown fences, explanations, or surrounding $ delimiters. "
            "If unreadable, return NOT_AVAILABLE."
        )
        if formula_hint:
            prompt = f"{prompt} Context hint: {formula_hint}"

        latex_text = self._invoke_multimodal(prompt=prompt, image_b64=image_b64)
        latex_text = latex_text.strip("`").strip()
        latex_text = latex_text.replace("$", "").strip()

        if not latex_text or latex_text.upper() == "NOT_AVAILABLE":
            return ""

        return latex_text
