import base64
import subprocess
from pathlib import Path

import requests


class OllamaVisionClient:
    def __init__(
        self,
        model: str = "gemma4:e4b",
        base_url: str = "http://localhost:11434",
        auto_pull: bool = True,
    ) -> None:
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.auto_pull = auto_pull
        self._model_ready = False

    def _fetch_available_models(self) -> set[str]:
        "returns a set of available Ollama model names"
        response = requests.get(f"{self.base_url}/api/tags", timeout=20)
        response.raise_for_status()

        payload = response.json()
        return {
            model["name"]
            for model in payload.get("models", [])
            if isinstance(model, dict) and model.get("name")
        }

    def _ensure_model(self) -> None:
        "Checks if the specified model is available, and pulls it if auto_pull is enabled. Uses subprocess to do that"
        if self._model_ready:
            return

        installed_models = self._fetch_available_models()
        if self.model not in installed_models:
            if not self.auto_pull:
                raise RuntimeError(
                    f"Vision model '{self.model}' is not installed. "
                    "Install it with: ollama pull <model-name>."
                )

            try:
                subprocess.run(["ollama", "pull", self.model], check=True)
            except subprocess.CalledProcessError as err:
                raise RuntimeError(
                    f"Failed to pull Ollama model '{self.model}': {err}"
                ) from err

        self._model_ready = True

    def describe_image(self, image_path: Path, caption_hint: str = "") -> str:
        self._ensure_model()

        with image_path.open("rb") as image_file:
            image_bytes = image_file.read()

        image_b64 = base64.b64encode(image_bytes).decode("ascii")

        prompt = (
            "You are describing a research-paper figure for a RAG system. "
            "Describe the figure content, key entities, trends, labels, and technical takeaway in 4-7 sentences. "
            "Do not hallucinate text that is not visible."
        )
        if caption_hint:
            prompt = f"{prompt} Caption hint: {caption_hint}"

        response = requests.post(
            f"{self.base_url}/api/generate",
            json={
                "model": self.model,
                "prompt": prompt,
                "images": [image_b64],
                "stream": False,
                "options": {"temperature": 0.0},
            },
            timeout=180,
        )
        response.raise_for_status()

        description = response.json().get("response", "").strip()
        if description:
            return description

        return "No visual description generated by the vision model."

    def transcribe_formula_latex(self, image_path: Path, formula_hint: str = "") -> str:
        self._ensure_model()

        with image_path.open("rb") as image_file:
            image_bytes = image_file.read()

        image_b64 = base64.b64encode(image_bytes).decode("ascii")

        prompt = (
            "You are a precise OCR assistant for mathematical expressions. "
            "Transcribe the equation in this image into valid LaTeX. "
            "Return only the LaTeX expression without markdown fences, explanations, or surrounding $ delimiters. "
            "If unreadable, return NOT_AVAILABLE."
        )
        if formula_hint:
            prompt = f"{prompt} Context hint: {formula_hint}"

        response = requests.post(
            f"{self.base_url}/api/generate",
            json={
                "model": self.model,
                "prompt": prompt,
                "images": [image_b64],
                "stream": False,
                "options": {"temperature": 0.0},
            },
            timeout=180,
        )
        response.raise_for_status()

        latex_text = response.json().get("response", "").strip()
        latex_text = latex_text.strip("`").strip()
        latex_text = latex_text.replace("$", "").strip()

        if not latex_text or latex_text.upper() == "NOT_AVAILABLE":
            return ""

        return latex_text
