"""add created_at and updated_at fields

Revision ID: 018d361a9f1d
Revises: 9a7b3c4d5e6f
Create Date: 2026-05-27 19:01:10.899220

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "018d361a9f1d"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "9a7b3c4d5e6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
