"""update document model

Revision ID: 0d165f42d9de
Revises: 8f7fb60104f2
Create Date: 2026-05-27 18:41:19.977893

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d165f42d9de"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "8f7fb60104f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("original_url", sa.String(), nullable=True))
    op.add_column("documents", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "name")
    op.drop_column("documents", "original_url")
    # ### end Alembic commands ###
