"""add visibility for threads

Revision ID: 13c8ea39af5f
Revises: f1a2b3c4d5e6
Create Date: 2026-06-03 07:55:28.019307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13c8ea39af5f"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("visibility", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "visibility")
    # ### end Alembic commands ###
