"""make thread name empty string by default

Revision ID: 1a6198c7481e
Revises: 13c8ea39af5f
Create Date: 2026-06-03 08:04:59.519009

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1a6198c7481e"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "13c8ea39af5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
