"""update chunk model

Revision ID: 6ccd788e9f3b
Revises: 0d165f42d9de
Create Date: 2026-05-27 18:58:40.463385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ccd788e9f3b"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "0d165f42d9de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents_chunks", sa.Column("order", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents_chunks", "order")
    # ### end Alembic commands ###
