"""add selection and reference id in chat

Revision ID: 76c0a2b91ade
Revises: fdeb2736e02f
Create Date: 2026-07-18 18:22:41.488379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76c0a2b91ade"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "fdeb2736e02f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_messages", sa.Column("selection", sa.String(), nullable=True))
    op.add_column(
        "chat_messages", sa.Column("reference_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "reference_id")
    op.drop_column("chat_messages", "selection")
    # ### end Alembic commands ###
