"""add chunk type

Revision ID: 7a6dc6a54c31
Revises: 557ce003788a
Create Date: 2026-05-31 19:27:07.485428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a6dc6a54c31"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "557ce003788a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("chunks", sa.Column("type", sa.String(), nullable=True))
    op.execute(
        sa.text(
            """
            UPDATE chunks
            SET type = COALESCE(NULLIF(extra->>'type', ''), 'text_chunk')
            WHERE type IS NULL
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "type")
    # ### end Alembic commands ###
