"""add default_voice_id on preferences

Revision ID: 83efbc1b90c3
Revises: 265e212698b7
Create Date: 2026-08-20 09:41:03.927632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "83efbc1b90c3"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "265e212698b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages_chunks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("chat_message_id", sa.String(), nullable=True),
        sa.Column("chunk_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_message_id"], ["chat_messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("chats_chunks")
    op.add_column(
        "preferences", sa.Column("default_voice_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preferences", "default_voice_id")
    op.create_table(
        "chats_chunks",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("chats_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("chunks_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["chats_id"],
            ["chats.id"],
            name=op.f("chats_chunks_chats_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chunks_id"],
            ["chunks.id"],
            name=op.f("chats_chunks_chunks_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chats_chunks_pkey")),
    )
    op.drop_table("chat_messages_chunks")
    # ### end Alembic commands ###
