"""add temp password on users.

Revision ID: 8f7fb60104f2
Revises: b27ffa384356
Create Date: 2026-05-27 17:58:30.272390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f7fb60104f2"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "b27ffa384356"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("temp_password", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("temp_password_expires_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "temp_password_expires_at")
    op.drop_column("users", "temp_password")
    # ### end Alembic commands ###
