"""add chunk content

Revision ID: b27ffa384356
Revises: 165ddbe9c967
Create Date: 2026-05-27 17:55:32.376151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b27ffa384356"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "165ddbe9c967"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunks", sa.Column("content", sa.String(), nullable=False))
    op.add_column("chunks", sa.Column("extra", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "extra")
    op.drop_column("chunks", "content")
    # ### end Alembic commands ###
